/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IntefaceGraphics.EMLOYER_INT;

import Classes.Employer;
import Classes.agence;
import IntefaceGraphics.Authenti;
import IntefaceGraphics.ALERT_INT.AlertPin;

/**
 *
 * @author pc
 */
public class EmpLoginInt extends javax.swing.JFrame {
    private agence a;
    private int cnt=2;
    /**
     * Creates new form Empint
     */
    public EmpLoginInt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Votre nom:");

        jPasswordField1.setText("1111");

        jLabel2.setText("Votre password:(tu as 3 tentations)");

        jButton1.setText("Valide");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                    jButton1ActionPerformed(evt);
                
            }
        });
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String pwd = new String(jPasswordField1.getPassword());
        String nom = new String(jTextField1.getText());
        int pin=Integer.parseInt(pwd);
        if(this.verifiePin(pin,nom)){
            this.setVisible(false);
            MenuPrinEmp c=new MenuPrinEmp(this.getEmployer(pin));
            c.setA(a);
            c.setLocationRelativeTo(null);
            c.setVisible(true);
        }else if(cnt>0){
            --cnt;
            jLabel2.setText("Votre password:("+(cnt+1)+" tentation)!!");
            AlertPin p=new AlertPin();
            p.setLocationRelativeTo(null);
            p.setVisible(true);
            }else{
                Authenti x=new Authenti();
                Authenti.setA(a);
                x.setLocationRelativeTo(null);
                x.setVisible(true);
                this.setVisible(false);
            }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration  
    public void setA(agence a) {
        this.a = a;
    } 
    public boolean verifiePin(int pin,String nom){
        int i;
        for(i=0;i<a.getNbem();i++){
           if(a.getEmp(i).getPin()==pin && a.getEmp(i).getNom().equals(nom)){
                return true;
           }
        }
        if(i==a.getNbem()) 
            return false;
        return false;
    } 
    public Employer getEmployer(int pin){
        Employer e=null;
        for(int i=0;i<a.getNbem();i++){
            if(a.getEmp(i).getPin()==pin){
              e=a.getEmp(i); 
            }
         }
        if(e!=null){
            return e;
        }else return null;
    }        
    public agence getA() {
        return a;
    }       
}
